#!/usr/bin/env python

import click
import requests
import json

from vegadns_cli.common import cli
import vegadns_cli.commands.accounts
import vegadns_cli.commands.domains
import vegadns_cli.commands.default_records
import vegadns_cli.commands.records
import vegadns_cli.commands.export
import vegadns_cli.commands.groups
import vegadns_cli.commands.groups
import vegadns_cli.commands.groupmembers
import vegadns_cli.commands.config
import vegadns_cli.commands.domaingroupmaps
import vegadns_cli.commands.updatedata
import vegadns_cli.commands.apikeys
import vegadns_cli.commands.upgrade
import vegadns_cli.commands.audit_logs


if __name__ == "__main__":
    cli(obj={})
